url: https://michael-collins.github.io/rothrock-furniture-co/
baseurl: /rothrock-furniture-co/

# Site settings
title: Rothrock Furniture Co
email: info@rothrockfurniture.com
description: "A website."


# Team names, titles and social links
people:
- name: Person
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Person
  pic: 2
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Person
  pic: 3
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: address
  - line: city, state zip

# Build settings
markdown: kramdown
permalink: pretty
